server:
  port: 8088
logging:
  level:
    org.springframework : debug

spring:
  messages:
    basename: messages

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
  hateoas:
    use-hal-as-default-json-media-type: false
#  security:
#    user:
#      name: username
#      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"
